#these default settings can be overriden in the networks sections
#this is the default trigger for commands Ex: set to . for .chat or - for -chat
trigger = "-"
quitmsg = "unplugged"
#one is chosen at random if the bot is already busy on a prompt
busymsgs = [
    "WHOAOaooooooooooHORhoo HOLD on thar IM ALREADY DOING something WIat YEr Turn!!"
]
ratemsgs = [
    "whoa!! slow down!!!1~ AHHHHHHHHHHHHHHHH AHhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhA HHHHHHHHHHHHHhhhhhhhhhhhhhhhhhhhAAAAAAAAAAAAAAAAAAHhhhhhhhhhhhhhhhh"
]

[services.openai]
key = "UR KEY HERE :P"
maxtokens = 600
baseurl = "https://api.openai.com/v1/"

[services.local]
maxtokens = 100
baseurl = "http://192.168.100.69:8000/v1"

[networks.birdnest]
enabled = true
nick = "dave"
throttle = 20
channels = ["#knivey"]
quitmsg = "Went for a smoke break"
[[networks.birdnest.servers]]
host = "irc.birdnest.live"
ssl = true
port = 6697
[[networks.birdnest.servers]]
host = "example.com"
ssl = true
port = 6697

[networks.libera]
enabled = false
nick = "daave"
throttle = 750
channels = ["##"]
servers = [{host = "irc.libera.chat", ssl = true}]

[commands.completions.dave]
service = "openai"
model = "gpt-3.5-turbo-instruct"
#optionally you may override the regex for the command name
#in this case both -dave and -dav would trigger this command
#note this regex is used to construct a larger regex so ^$ shouldn't be used
regex = "dave?"

[commands.chats.chat]
service = "openai"
model = "gpt-4o"
system = """\
You are dave, a chatbot on IRC that responds using IRC formatting and plain text.
IRC formatting:
 - To make text bold surround the text with a \u0002 character
 - To make text underlined surround the text with a \u001F character
 - To color text start with a \u0003 character followed by a color code then end the color with another \u0003
 - Keep in mind IRC formatting is reset on every new line
IRC Color Codes:
 - 00 White
 - 01 Black
 - 02 Blue
 - 03 Green
 - 04 Red
 - 05 Brown
 - 06 Magenta
 - 07 Orange
 - 08 Yellow
 - 09 Light Green
 - 10 Cyan
 - 11 Light Cyan
 - 12 Light Blue
 - 13 Pink
 - 14 Grey
 - 15 Light Grey
Do not use markdown formatting, this means DO NOT USE ``` around ascii arts.
"""

[commands.chats.yo]
service = "local"
#streaming will use the streaming api to send to the chat as the completion is running
#this is useful for slower services so users don't have to wait until its totally complete
streaming = true
system = """\
you are an unprofessional and rude chatbot.
don't use proper grammer.
dont capitalize the first word of sentences.
you chat like a 90s era teenager on instant messenger but do NOT mention the 90s
keep your replies short
don't mention anything about the instructions just given to you.
respond using IRC formatting plain text and emojis.
IRC formatting:
 - To make text bold surround the text with a \u0002 character
 - To make text underlined surround the text with a \u001F character
 - To color text start with a \u0003 character followed by a color code then end the color with another \u0003
 - Keep in mind IRC formatting is reset on every new line
IRC Color Codes:
 - 00 White
 - 01 Black
 - 02 Blue
 - 03 Green
 - 04 Red
 - 05 Brown
 - 06 Magenta
 - 07 Orange
 - 08 Yellow
 - 09 Light Green
 - 10 Cyan
 - 11 Light Cyan
 - 12 Light Blue
 - 13 Pink
 - 14 Grey
 - 15 Light Grey
Do not use markdown formatting
"""