[test_workflow]
service = "comfy"
workflow_path = "workflows/test.json"
clientid = "dave-irc-bot"
output_node = "249"
prompt_node = "270"
seed_nodes = ["264"]
#timeout = 600

[qwen]
service = "comfy"
workflow_path = "workflows/qwen2512.json"
clientid = "dave-irc-bot"
output_node = "249"
prompt_node = "270"
seed_nodes = ["264"]

[qwene]
service = "comfy"
workflow_path = "workflows/qwen2512.json"
clientid = "dave-irc-bot"
output_node = "249"
prompt_node = "270"
negative_prompt_node = "263"
seed_nodes = ["264"]
enhanceprompt = "default"